import type {Metadata} from "next";
import {Inter as FontSans} from "next/font/google";
import "./globals.css";

import {cn} from "@/lib/utils";
import {SocketProvider} from "@/contexts/Socket";
import {AuthProvider} from "@/contexts/AuthContext";
import Layout from "@/components/assets/Layout";

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
});

export const metadata: Metadata = {
    title: "Quizz Marseille BB",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={cn(
                "min-h-screen bg-background font-sans antialiased",
                fontSans.variable
            )}
        >
        <SocketProvider>
            <AuthProvider>
                <Layout>
                    {children}
                </Layout>
            </AuthProvider>
        </SocketProvider>
        </body>
        </html>
    );
}
